
const ideologies = [
  { name: "Anarcho-Capitalism", values: [9.4, -9.5, 0] },
  { name: "Minarcho-Capitalism", values: [7, -9.5, 0] },
  //{ name: "Hoppeanism", values: [9.5, -9.5, -4] },
  { name: "Left-Rothbardianism", values: [6.8, -9.2, 0] },
  //{ name: "Anarcho-Feudalism", values: [6, -8.2, -5] },
  { name: "Right-Libertarianism", values: [7, -6, 0] },
  { name: "Social Libertarianism", values: [3, -6, 0] },
  { name: "Jeffersonianism", values: [5.5, -3, 0] },
  { name: "Bleeding-Heart Libertarianism", values: [5.2, -6, 2] },
  { name: "Conservative Libertarianism", values: [5.7, -6, -2] },
  { name: "Georgist Libertarianism", values: [4.5, -5.5, 0] },
  { name: "Classical Liberalism", values: [6, -3.3, 0] },
  { name: "Georgism", values: [1, -3, 0] },
  { name: "Libertarian Distributism", values: [1, -5, 0] },
  { name: "Hayekianism", values: [5, -6.8, 0] },
  { name: "Austrolibertarianism", values: [9.2, -5, 0] },
  //{ name: "Objectivist Minarchism", values: [10, -7.2, 0] },
  //{ name: "Randian Anarcho-Egoism", values: [10, -10, 0] },
  { name: "Propertarianism", values: [10, -3, 0] },
  { name: "Anarcho-Individualism", values: [1.2, -10, 0] },
  { name: "Agorism", values: [3.2, -9.8, 0] },
  { name: "Anarcho-Distributism", values: [-1, -7, 0] },

  { name: "Juche", values: [-9.5, 9.5, 0] },
  { name: "British Fascism", values: [-2, 7, 0] },
  { name: "Italian Fascism", values: [-5, 9, 0] },
  { name: "Clerical \"Fascism\"", values: [1.2, 9.2, -5] },
  { name: "National Socialism", values: [-3, 8.5, -3] },
  { name: "Brazilian Integralism", values: [-1, 7, 0] },
  { name: "Corporatism", values: [-3, 7, 0] },
  { name: "Orthodox Futurism", values: [-5, 8.5, 3] },
  { name: "Peronism", values: [-6.5, 6.5, 0] },
  { name: "Falangism", values: [-4, 7, 0] },
  { name: "Strasserism", values: [-7, 7.7, -3] },
  { name: "3rd Internat. Theory", values: [-8.5, 6, -1] },
  { name: "Fourth Theory", values: [-7, 9, -2] },
  { name: "Titoism", values: [-3, 5, 0] },
  { name: "Nazi-Maoism", values: [-9, 9.5, -4] },
  { name: "National Syndicalism", values: [-7.2, 9, -0] },
  { name: "Folkish Syndicalism", values: [-9, 9, -2.5] },
  { name: "Crus. O' Romanianism", values: [-8, -4, -3] },
  { name: "Stalinism", values: [-8.5, 9.5, -2] },

  { name: "Leninism", values: [-10, 7.2, 0] },
  { name: "Paetelianism", values: [-10, 7.5, -3] },
  { name: "Trotskyism", values: [-10, 5, 0] },
  { name: "Italian Left-Communism", values: [-10, 3, 0] },
  { name: "Classical Marxism", values: [-10, 1, 0] },
  { name: "Democratic Socialism", values: [-5, 3, 0] },
  { name: "Montagnardism", values: [-3, 3, 0] },

  { name: "Council Communism", values: [-10, -3, 0] },
  { name: "Democratic Confederalism", values: [-5, -5, 0] },
  { name: "Guild Socialism", values: [-5, -3, 0] },
  { name: "Libertarian Socialism", values: [-7, -5, 0] },
  { name: "Liberal Socialism", values: [-5, -1, 0] },
  { name: "Radical Liberalism", values: [-3, -1, 0] },
  { name: "Minarcho-Socialism", values: [-7, -7, 0] },
  { name: "Libertarian Market Socialism", values: [-3, -5, 0] },
  { name: "Anarcho-Communism", values: [-9.5, -9.5, 0] },
  { name: "Anarcho-Syndicalism", values: [-10, -7, 0] },
  { name: "National Anarchism", values: [-8, -8.5, -2] },
  { name: "Social Anarchism", values: [-5, -9, 0] },
  { name: "Odalism", values: [-3, -7, -2] },
  { name: "Anarcho-Mutualism", values: [-3, -9.3, 0] },
  { name: "Stirnerite Anarcho-Egoism", values: [-1.2, -10, 2] },
  
  { name: "Paternalistic Conservatism", values: [1, 5, 0] },
  
  { name: "Third Way", values: [1, -1, 0] },
  { name: "Modern Liberalism", values: [-1, -1, 0] },
  { name: "Right-Liberalism", values: [3, -3, 0] },
  { name: "Ordoliberalism", values: [3, 3, 0] },
  { name: "Neoliberalism", values: [5, -1, 0] },
  { name: "Neolibertarianism", values: [7, -1, 0] },
  { name: "Keynsian Liberalism", values: [1, 1, 0] },
  { name: "Social Capitalism", values: [-3, -3, 0] },
  { name: "Progressives", values: [-1, -3, 0] },
  { name: "Conservatives", values: [3, -1, -0] },
  { name: "Distributism", values: [-1, 1, 0] },

  { name: "Neocameralism", values: [7.2, 1, 0] },
  { name: "Darwinian Liberalism", values: [10, 1, 0] },
  { name: "Reactionary \"Liberalism\"", values: [10, -1, 0] },
  { name: "Timocracy", values: [10, 3, 0] },
  { name: "American Confederatism", values: [8, 4, -0] },
  { name: "Reactionarism", values: [8.5, 4, -6] },
  { name: "Hamiltonianism", values: [5, 4.5, 0] },
  { name: "State Capitalism", values: [3, 5, 0] },
  { name: "Carlism", values: [5, 7, 0] },
  { name: "Stakeholder Capitalism", values: [1, 5, 0] },
  { name: "Cameralism", values: [1, 7, 0] },
  { name: "Mesoconservatism", values: [7, 6.5, 0] },
  { name: "Aristocracy", values: [10, 7, 0] },
  { name: "Francoism", values: [3, 9, 0] },
  { name: "Optimateism", values: [5, 9, 0] },
  { name: "Corporatocracy", values: [5, 7, 2] },
  { name: "Autocratic Capitalism", values: [9, 9.2, 0] },
  { name: "Totalist Capitalism", values: [7, 9.2, 0] },
  { name: "National Distributism", values: [1, 5.5, 0] },
];