questions =  [
    {"id": 0, "question": "People's needs should be met unconditionally.", "effects": {"right": -1}},
    {"id": 1, "question": "Those who don’t work should not expect support.", "effects": {"right": 1}},
    {"id": 2, "question": "Taxation should be abolished in a capitalist mode of production.", "effects": {"right": 1}},
    {"id": 3, "question": "For a genuine free market, regulation is needed to prevent monopolies.", "effects": {"right": -1}},
    {"id": 4, "question": "Those with the ability to pay should have access to higher standards of medical care. ", "effects": {"right": 1}},
    {"id": 5, "question": "Taxation of the rich is a bad idea.", "effects": {"right": 1}},
    {"id": 6, "question": "Class division isn’t as bad as people say it is.", "effects": {"right": 1}},
    {"id": 7, "question": "Selfishness is a virtue.", "effects": {"right": 1}},
    {"id": 8, "question": "Class systems are important for a functioning society.", "effects": {"right": 1}},
    {"id": 9, "question": "Weaker individuals will be eliminated naturally, and we should embrace this.", "effects": {"right": 1}},
    {"id": 10, "question": "Markets are the best way to allocate resources.", "effects": {"right": 1}},
    {"id": 11, "question": "Competition drives innovation.", "effects": {"right": 1}},
    {"id": 12, "question": "Welfare is a right of all people.", "effects": {"right": -1}},
    {"id": 13, "question": "The state should intervene in the economy whenever needed.", "effects": {"right": -1}},
    {"id": 14, "question": "Social stratification should be opposed.", "effects": {"right": -1}},
    {"id": 15, "question": "Private ownership should be limited.", "effects": {"right": -1}},
    {"id": 16, "question": "From each according to his ability, to each according to his need.", "effects": {"right": -1}},
    {"id": 17, "question": "Land shouldn’t be a commodity to be bought and sold. ", "effects": {"right": -1}},
    {"id": 18, "question": "Trickle-down economic theory is false.", "effects": {"right": -1}},
    {"id": 19, "question": "Political authority of the state is legitimate.", "effects": {"auth": 1}},
    {"id": 20, "question": "People with serious inheritable disabilities should not be allowed to reproduce. ", "effects": {"auth": 1}},
    {"id": 21, "question": "Abortion should often be illegal.", "effects": {"auth": 1}},
    {"id": 22, "question": "The state should permeate all facets of society.", "effects": {"auth": 1}},
    {"id": 23, "question": "There is no such thing as individualism.", "effects": {"auth": 1}},
    {"id": 24, "question": "The state, if it must exist, should be minimized to only bare functions.", "effects": {"auth": -1}},
    {"id": 25, "question": "Free speach is vital for a healthy society.", "effects": {"auth": -1}},
    {"id": 26, "question": "Your right to swing your arms ends where another man's nose begins.", "effects": {"auth": -1}},
    {"id": 27, "question": "The state has its very origins in coercive aggression.", "effects": {"auth": -1}},
    {"id": 28, "question": "Conformity is a value that should be upheld.", "effects": {"prog": -1}},
    {"id": 29, "question": "The enlightenment was a mistake.", "effects": {"prog": -1}},
    {"id": 30, "question": "I oppose immigration.", "effects": {"prog": -1}},
    {"id": 31, "question": "Family values are sacred and should be protected.", "effects": {"prog": -1}},
    {"id": 32, "question": "Bigotry should be opposed at every turn.", "effects": {"prog": 1}},
    {"id": 33, "question": "There is no point in conserving cultural norms.", "effects": {"prog": 1}},
    {"id": 34, "question": "Tradition is antithetical to reason.", "effects": {"prog": 1}},
     {"id": 35, "question": "We should get rid of oppressive traditions", "effects": {"prog": 1}}
];