questions = [
    {"id": 0, "question": "Cities, towns, and large plots of land should be privately owned and be made solely for the interests of its owners.", "effects": {"right": 1}},
    {"id": 1, "question": "The market economy is the most efficient and/or ethical means of producing and distributing goods and services.", "effects": {"right": 1}},
    {"id": 2, "question": "Regulations on goods and services are detrimental to the economy and to private property.", "effects": {"right": 1}},
    {"id": 3, "question": "Taxation or wealth distribution based on income, trade or property is not ideal and should be lowered or abolished entirely.", "effects": {"right": 1}},
    {"id": 4, "question": "Questions of law should be defined by who owns property.", "effects": {"right": 1}},
    {"id": 5, "question": "Wealth disparity of class groups is due to some individuals working harder.", "effects": {"right": 1}},
    {"id": 6, "question": "The welfare state should be abolished and replaced with voluntary charitable organizations.", "effects": {"right": 1}},
    {"id": 7, "question": "Property is odious in its principle and murderous in its effects.", "effects": {"right": -1}},
    {"id": 8, "question": "It is wasteful to have multiple brands of the same good.", "effects": {"right": -1}},
    {"id": 9, "question": "Essential goods and industries, like water, healthcare, or housing, should not be commodified or left solely to the market.", "effects": {"right": -1}},
    {"id": 10, "question": "Economic class systems are divisive.", "effects": {"right": -1}}, 
    {"id": 11, "question": "Cooperative and democratic workplace models are preferable to hierarchical ones.", "effects": {"right": -1}},
    {"id": 12, "question": "Infrastructure, like roads, power grids, or internet access should be publicly owned.", "effects": {"right": -1}},
    {"id": 13, "question": "Wage amounts should not be delegated solely to employers and should be handled or regulated by the state or community.", "effects": {"right": -1}},
    {"id": 14, "question": "Identification and surveillance techniques should be used to ensure public safety.", "effects": {"auth": 1}},
    {"id": 15, "question": "The government should have the authority to regulate or influence any interactions between two or more consenting parties.", "effects": {"auth": 1}},
    {"id": 16, "question": "The government should be used to incentivize people towards or away from certain actions.", "effects": {"auth": 1}},
    {"id": 17, "question": "It is the government's responsibility to enforce morality.", "effects": {"auth": 1}},
    {"id": 18, "question": "Individualism is an unhealthy scourge of a culture.", "effects": {"auth": 1}},
    {"id": 19, "question": "The government is the only entity that can fairly and effectively regulate institutions and organizations.", "effects": {"auth": 1}},
    {"id": 20, "question": "Smaller, local communities or governments are preferable to large, centralized states.", "effects": {"auth": -1}},
    {"id": 21, "question": "People should be able to do whatever they want with their own bodies.", "effects": {"auth": -1}},
    {"id": 22, "question": "If the government must exist, it ought to be minimized to only bare functions such as emergency services, law & defense, or welfare.", "effects": {"auth": -1}},
    {"id": 23, "question": "The state ought to be a means to an end; it (likely) should not last in its current size forever.", "effects": {"auth": -1}},
    {"id": 24, "question": "Acts and organizations, like jury duty or public schools, made compulsory by the state, are evil and should be abolished.", "effects": {"auth": -1}},
    {"id": 25, "question": "Large state bureaucracies & administrations are wasteful/evil and should be minimized or abolished whenever possible.", "effects": {"auth": -1}},
    {"id": 26, "question": "The concept of society and social norms should be abolished entirely.", "effects": {"prog": 1}},
    {"id": 27, "question": "Tradition is antithetical to reason.", "effects": {"prog": 1}},
    {"id": 28, "question": "Gender-and-sexuality-nonconforming individuals should be accepted for who they are.", "effects": {"prog": 1}},
    {"id": 29, "question": "Sexual deviancy is perfectly fine.", "effects": {"prog": 1}},
    {"id": 30, "question": "People shouldn't be treated harshly solely because of some immutable characteristics.", "effects": {"prog": 1}},
    {"id": 31, "question": "Those of different status or ability should still be treated with respect.", "effects": {"prog": 1}},
    {"id": 32, "question": "Cultural adaptation to foreign ideas and values is necessary for societies to thrive in the modern world.", "effects": {"prog": 1}},
    {"id": 33, "question": "Autonomy of body extends even to minors or the mentally ill.", "effects": {"prog": 1}},
    {"id": 34, "question": "Different kinds of people should ideally keep within their own kin.", "effects": {"prog": -1}},
    {"id": 35, "question": "Political systems that were widely established in past centuries are better than the ones in place now.", "effects": {"prog": -1}},
    {"id": 36, "question": "Cultural and societal traditions strengthen communities and society at large.", "effects": {"prog": -1}},
    {"id": 37, "question": "We ought to return to a simpler lifestyle.", "effects": {"prog": -1}},
    {"id": 38, "question": "Traditional gender roles ought to be maintained.", "effects": {"prog": -1}},
    {"id": 39, "question": "Abortion is abhorrent and ought to be made illegal.", "effects": {"prog": -1}},
    {"id": 40, "question": "Drug and substance usage are immoral acts and should be socially punished.", "effects": {"prog": -1}},
    {"id": 41, "question": "Religion and culture ought to influence laws of communities and governments.", "effects": {"prog": -1}}
];
